Repository prgrms-web-devcourse-final-project/WEB4_5_GAEPPADAK_BE, pull requests merged in 2025-04, with the labels that each got.

#2 Chore/1 GitHub workflows setting
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/issue-branch.yml
  .github/pull_request_template.md
  .github/workflows/create-branch-for-issue.yml
  .github/workflows/pull-request-ci.yml
  .github/workflows/pull-request-reviewers.yml
Labels: chore

#9 Chore/5 README 병합
  README.md
Labels: docs

#13 Feat/11 add base entity and swagger
  backend/build.gradle
  backend/docker-compose.yaml
  backend/src/main/java/site/kkokkio/KkokkioApplication.java
  backend/src/main/java/site/kkokkio/global/util/BaseTimeEntity.java
  backend/src/main/resources/application.yml
Labels: feature

#14 Chore/12 securityconfig setting
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
Labels: chore

#16 Chore/15 redis setting
  backend/build.gradle
  backend/docker-compose.yaml
  backend/src/main/java/site/kkokkio/global/config/RedisConfig.java
  backend/src/main/resources/application.yml
Labels: chore

#20 Feat/19 setup rsdata
  backend/src/main/java/site/kkokkio/global/aspect/ResponseAspect.java
  backend/src/main/java/site/kkokkio/global/dto/Empty.java
  backend/src/main/java/site/kkokkio/global/dto/RsData.java
  backend/src/main/java/site/kkokkio/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/site/kkokkio/global/exception/ServiceException.java
Labels: feature

#18 Feat/10 setup entity and migration
  .gitignore
  .nvmrc
  README.md
  backend/V1__init.sql
  backend/build.gradle
  backend/docker-compose.yaml
  backend/flyway.conf
  backend/package.json
  backend/src/main/java/site/kkokkio/domain/comment/entity/Comment.java
  backend/src/main/java/site/kkokkio/domain/comment/entity/CommentLike.java
  backend/src/main/java/site/kkokkio/domain/keyword/entity/Keyword.java
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordMetricHourly.java
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordMetricHourlyId.java
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordPostHourly.java
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordPostHourlyId.java
  backend/src/main/java/site/kkokkio/domain/member/entity/Member.java
  backend/src/main/java/site/kkokkio/domain/post/entity/Post.java
  backend/src/main/java/site/kkokkio/domain/post/entity/PostKeyword.java
  backend/src/main/java/site/kkokkio/domain/post/entity/PostMetricHourly.java
  backend/src/main/java/site/kkokkio/domain/post/entity/PostSource.java
  backend/src/main/java/site/kkokkio/domain/source/entity/Source.java
  backend/src/main/java/site/kkokkio/global/enums/MemberRole.java
  backend/src/main/java/site/kkokkio/global/enums/Platform.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prd.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V1__init.sql
  package.json
Labels: feature

#24 feat: SwaggerConfig add
  backend/src/main/java/site/kkokkio/global/config/SwaggerConfig.java
Labels: feature

#29 Feat/23 add comment
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentController.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/CommentCreateRequest.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/CommentListResponse.java
  backend/src/main/java/site/kkokkio/domain/comment/dto/CommentDto.java
  backend/src/main/java/site/kkokkio/domain/comment/entity/Comment.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentLikeRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostRepository.java
Labels: feature

#28 Feat: 구글 트렌드 인기 키워드 조회 기능 구현
  backend/build.gradle
  backend/src/main/java/site/kkokkio/domain/keyword/controller/GoogleTrendsController.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyController.java
  backend/src/main/java/site/kkokkio/domain/keyword/dto/KeywordMetricHourlyResponse.java
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordMetricHourlyId.java
  backend/src/main/java/site/kkokkio/domain/keyword/repository/KeywordMetricHourlyRepository.java
  backend/src/main/java/site/kkokkio/domain/keyword/repository/KeywordRepository.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/GoogleTrendsRssService.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyService.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordService.java
Labels: feature

#39 Feat/33 get post source api
  backend/build.gradle
  backend/src/main/java/site/kkokkio/KkokkioApplication.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/domain/source/controller/SourceControllerV1.java
  backend/src/main/java/site/kkokkio/domain/source/controller/dto/SourceListResponse.java
  backend/src/main/java/site/kkokkio/domain/source/dto/SourceDto.java
  backend/src/main/java/site/kkokkio/domain/source/entity/PostSource.java
  backend/src/main/java/site/kkokkio/domain/source/entity/Source.java
  backend/src/main/java/site/kkokkio/domain/source/port/out/SourceNewsPort.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/repository/SourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/main/java/site/kkokkio/global/config/JpaAuditingConfig.java
  backend/src/main/java/site/kkokkio/global/dto/Empty.java
  backend/src/main/java/site/kkokkio/global/dto/RsData.java
  backend/src/main/java/site/kkokkio/global/enums/Platform.java
  backend/src/main/java/site/kkokkio/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/db/migration/V1__init.sql
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
Labels: feature

#40 Feat/36 comment test
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/CommentCreateRequest.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
Labels: test

#30 Feat/21 join login
  .github/workflows/pull-request-ci.yml
  backend/build.gradle
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/MemberLoginRequest.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/MemberLoginResponse.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/MemberResponse.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/MemberSignUpRequest.java
  backend/src/main/java/site/kkokkio/domain/member/repository/MemberRepository.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/exception/CustomAuthException.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
  backend/src/main/resources/application.yml
Labels: feature

#48 Build/6 CI/CD - dockerfile 추가
  .github/workflows/deploy.yml
  backend/DockerFile
Labels: build, HOTFIX

#46 Feat/37 email verify check
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/MemberLoginResponse.java
  backend/src/main/java/site/kkokkio/domain/member/dto/EmailVerificationRequest.java
  backend/src/main/java/site/kkokkio/domain/member/entity/Member.java
  backend/src/main/java/site/kkokkio/domain/member/service/MailService.java
  backend/src/main/java/site/kkokkio/global/config/MailConfig.java
  backend/src/main/java/site/kkokkio/global/exception/GlobalExceptionHandler.java
  backend/src/main/resources/application.yml
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MailServiceTest.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
Labels: feature

#47 Feat/25 set popular keyword for take youtube and naver news content
  backend/src/main/java/site/kkokkio/domain/source/controller/SourceControllerV1.java
  backend/src/main/java/site/kkokkio/domain/source/controller/dto/TopSourceListResponse.java
  backend/src/main/java/site/kkokkio/domain/source/dto/TopSourceItemDto.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
Labels: feature

#50 Chore/6 workflows - 환경변수 추가 및 파일 이름 변경
  backend/Dockerfile
  infra/main.tf
  infra/variable.tf
Labels: build

#53 Chore/6 workflows - 깃헙액션에서 깃헙 환경변수 사용, ec2에 도플러 cli 설치되도록 수정 및 prefix 변경
  .github/workflows/deploy.yml
  infra/main.tf
  infra/variable.tf
Labels: build

#54 Feat/38 swagger custom annotation
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV1.java
  backend/src/main/java/site/kkokkio/domain/source/controller/SourceControllerV1.java
  backend/src/main/java/site/kkokkio/global/config/SwaggerConfig.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ApiErrorCodeExamples.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ExampleHolder.java
  backend/src/main/resources/application.yml
Labels: docs

#58 Refactor/55 pagination meta
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/CommentListResponse.java
  backend/src/main/java/site/kkokkio/domain/source/controller/dto/TopSourceListResponse.java
  backend/src/main/java/site/kkokkio/global/dto/PaginationMeta.java
Labels: refactor

#59 Feat/56 update db schema source keyword
  backend/gradlew
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordMetricHourly.java
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordPostHourly.java
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordPostHourlyId.java
  backend/src/main/java/site/kkokkio/domain/keyword/repository/KeywordMetricHourlyRepository.java
  backend/src/main/java/site/kkokkio/domain/keyword/repository/KeywordPostHourlyRepository.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/GoogleTrendsRssService.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/domain/source/entity/KeywordSource.java
  backend/src/main/java/site/kkokkio/domain/source/repository/KeywordSourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/V1__init.sql
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: feature

#61 Chore/6 workflows - 배포가 deploy에서만 작동하도록 수정
  infra/main.tf
  infra/variable.tf
Labels: build, chore

#63 Feat/60 naver open api mocking
  backend/src/main/java/site/kkokkio/infra/naver/news/NaverNewsApiAdapter.java
  backend/src/main/resources/application-prd.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/mock/naver-news-search.json
  backend/src/test/java/site/kkokkio/infra/naver/news/NaverNewsApiAdapterMockTest.java
  backend/src/test/java/site/kkokkio/infra/naver/news/NaverNewsApiAdapterTest.java
Labels: feature

#62 Chore/6 workflows - deploy 수정
  .github/workflows/deploy.yml
Labels: build, chore
