Repository prgrms-web-devcourse-final-project/WEB4_5_GAEPPADAK_BE, pull requests merged in 2025-05, with the labels that each got.

#64 Feat/keyword search
  backend/src/main/java/site/kkokkio/domain/keyword/controller/GoogleTrendsController.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/KeywordControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/GoogleTrendsRssService.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordService.java
  backend/src/main/java/site/kkokkio/domain/post/dto/PostListResponse.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostKeywordRepository.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostRepository.java
  backend/src/test/java/site/kkokkio/domain/keyword/controller/KeywordControllerTest.java
  backend/src/test/java/site/kkokkio/domain/keyword/service/GoogleTrendsRssServiceTest.java
  backend/src/test/java/site/kkokkio/domain/keyword/service/KeywordServiceTest.java
Labels: feature

#66 Deploy
  .github/workflows/deploy.yml
  backend/Dockerfile
  infra/main.tf
Labels: build

#76 빌드 및 배포 브랜치 develop으로 다시 변경
  .github/workflows/deploy.yml
Labels: build, chore

#75 feat: baseInitData 회원 입력 & SecurityConfig 설정 & 프론트URL(임시)설정
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/init/BaseInitData.java
  backend/src/main/java/site/kkokkio/global/security/CustomUserDetailsService.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
Labels: feature

#78 Feat/34 get hot sources from keyword api
  backend/V1__init.sql
  backend/src/main/java/site/kkokkio/domain/keyword/controller/KeywordControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/dto/KeywordSearchSourceListResponse.java
  backend/src/main/java/site/kkokkio/domain/source/controller/SourceControllerV1.java
  backend/src/main/java/site/kkokkio/domain/source/dto/SourceDto.java
  backend/src/main/java/site/kkokkio/domain/source/repository/SourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/test/java/site/kkokkio/domain/keyword/controller/KeywordControllerTest.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
  doppler.yaml
Labels: feature

#83 개발 배포 환경에 맞춰 Dockerfile 변경
  backend/Dockerfile
Labels: build, chore

#88 redis 호스트와 포트를 환경변수로 변경
  backend/src/main/resources/application.yml
Labels: bug

#89 ec2 서버가 재시작 될 때 백엔드 서버도 자동 재시작 되도록 수정
  .github/workflows/deploy.yml
  backend/Dockerfile
  infra/main.tf
Labels: build, chore

#85 Fix/82 batch job with test
  backend/build.gradle
  backend/src/main/java/site/kkokkio/domain/keyword/entity/Keyword.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordService.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostKeywordRepository.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostKeywordRepositoryCustom.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostKeywordRepositoryCustomImpl.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/domain/source/entity/KeywordSource.java
  backend/src/main/java/site/kkokkio/domain/source/entity/Source.java
  backend/src/main/java/site/kkokkio/domain/source/repository/KeywordSourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/repository/KeywordSourceRepositoryCustom.java
  backend/src/main/java/site/kkokkio/domain/source/repository/KeywordSourceRepositoryCustomImpl.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepositoryCustom.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepositoryCustomImpl.java
  backend/src/main/java/site/kkokkio/domain/source/repository/SourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/repository/SourceRepositoryCustom.java
  backend/src/main/java/site/kkokkio/domain/source/repository/SourceRepositoryCustomImpl.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/main/java/site/kkokkio/global/scheduler/HourScheduler.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prd.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/site/kkokkio/domain/keyword/service/KeywordServiceTest.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
  backend/src/test/java/site/kkokkio/domain/source/service/OpenGraphServiceTest.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
Labels: bug, feature

#91 feat: front URL추가
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
Labels: chore

#95 fix: 프론트 URL 3000 포트 허용
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
Labels: HOTFIX

#93 Feat/77 add search youtube and mock testcode
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/main/java/site/kkokkio/infra/youtube/video/YoutubeVideoApiAdapter.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/mock/youtube-videos-search.json
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
  backend/src/test/java/site/kkokkio/infra/youtube/video/YoutubeVideoApiAdapterMockTest.java
  backend/src/test/java/site/kkokkio/infra/youtube/video/YoutubeVideoApiAdapterTest.java
Labels: feature, chore

#98 Feat/97 token exception
  backend/src/main/java/site/kkokkio/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
Labels: feature

#101 Feat/99 GET /member/me 구현(회원정보조회)
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/test/java/site/kkokkio/domain/member/controller/AuthControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
Labels: feature

#103 Fix/102 500 error modify
  backend/src/main/java/site/kkokkio/domain/source/dto/TopSourceItemDto.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
Labels: bug

#108 Feat/80 jwt filter
  backend/.gitignore
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/AuthService.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/filter/JwtAuthenticationFilter.java
  backend/src/main/java/site/kkokkio/global/security/CustomUserDetails.java
  backend/src/main/java/site/kkokkio/global/security/CustomUserDetailsService.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/keyword/controller/KeywordControllerTest.java
  backend/src/test/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/controller/AuthControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/AuthServiceV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
Labels: feature

#111 Feat/109 post mock add
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV1.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mock/post-search.json
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: feature

#112 posts/top에서 post가 비었을 때 빈 배열을 보내도록 수정
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: chore

#114 Fix/113 post mock 500 error
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
Labels: bug

#116 Fix/115 fix 500
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
Labels: bug

#119 Fix/118 mock 500error
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
Labels: bug

#121 Fix/120 500error
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/resources/mock/post-search.json
Labels: bug

#124 Feat/117 comment fix
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/dto/CommentDto.java
  backend/src/main/java/site/kkokkio/domain/comment/entity/Comment.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentLikeRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/global/filter/JwtAuthenticationFilter.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
Labels: feature

#130 fix: add id key and pagination meta object at /posts/search/sources api
  backend/src/main/java/site/kkokkio/domain/keyword/controller/KeywordControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/dto/KeywordSearchSourceListResponse.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV1.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/PostSearchSourceListResponse.java
  backend/src/main/java/site/kkokkio/domain/source/dto/SourceDto.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/test/java/site/kkokkio/domain/keyword/controller/KeywordControllerTest.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
Labels: bug

#137 build: 프로덕션 배포 트리거를 main 브랜치로 변경
  .github/workflows/deploy-prd.yml
Labels: build, chore

#141 Docs/README에 배포 주소 추가
  README.md
Labels: docs, chore

#142 fix: naver news description add and fix test code
  backend/src/main/java/site/kkokkio/domain/source/dto/TopSourceItemDto.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
Labels: bug

#146 chore: 백엔드 prod API 주소 CORS 허용
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
Labels: chore

#148 Refactor/빌드시 배포 환경에 맞게 빌드되도록 Dockerfile 분리
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prd.yml
  backend/Dockerfile.dev
  backend/Dockerfile.prd
  infra/dev/main.tf
  infra/prd/main.tf
Labels: build, refactor

#149 Refactor/빌드 앤 푸시에서 context와 file 변경
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prd.yml
Labels: build, refactor

#153 fix: fix mock.enabled config and add scheduler test api
  backend/src/main/java/site/kkokkio/domain/admin/controller/BatchJobControllerV1.java
  backend/src/main/resources/application-prd.yml
Labels: bug

#155 Feat/154 add id in rest api response
  backend/src/main/java/site/kkokkio/domain/comment/dto/CommentDto.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/PostSearchSourceListResponse.java
  backend/src/main/java/site/kkokkio/domain/source/controller/dto/SourceListResponse.java
  backend/src/main/java/site/kkokkio/domain/source/dto/NewsDto.java
  backend/src/main/java/site/kkokkio/domain/source/dto/SourceDto.java
  backend/src/main/java/site/kkokkio/domain/source/dto/TopSourceItemDto.java
  backend/src/main/java/site/kkokkio/domain/source/dto/VideoDto.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/main/java/site/kkokkio/infra/youtube/video/YoutubeVideoApiAdapter.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
  backend/src/test/java/site/kkokkio/infra/youtube/video/YoutubeVideoApiAdapterMockTest.java
  backend/src/test/java/site/kkokkio/infra/youtube/video/YoutubeVideoApiAdapterTest.java
Labels: feature

#156 Fix/152 refresh token info
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/dto/TokenDto.java
  backend/src/main/java/site/kkokkio/domain/member/service/AuthService.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
  backend/src/test/java/site/kkokkio/domain/member/controller/AuthControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/AuthServiceV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
Labels: bug

#158 Feat/68 email verified 2
  backend/docker-compose.yaml
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/AuthService.java
  backend/src/main/java/site/kkokkio/domain/member/service/MailService.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/config/RedisListenerConfig.java
  backend/src/main/java/site/kkokkio/global/filter/JwtAuthenticationFilter.java
  backend/src/main/java/site/kkokkio/global/listener/RedisExpiredKeyListener.java
  backend/src/test/java/site/kkokkio/domain/member/service/AuthServiceV1Test.java
Labels: feature

#168 Bug/164 api modifiy
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/AuthService.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
Labels: bug

#167 Bug/161 comment qa fix
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  package-lock.json
  package.json
Labels: bug

#166 bug/RsData response에서 데이터가 없을 때 빈 data를 받는 문제를 수정
  backend/src/main/java/site/kkokkio/global/dto/RsData.java
Labels: bug

#176 Fix/165 fix error code
  backend/src/main/java/site/kkokkio/domain/source/controller/SourceControllerV1.java
  backend/src/main/java/site/kkokkio/domain/source/dto/SourceDto.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
Labels: bug

#174 feat: setup local timezone to Seoul
  backend/src/main/resources/application.yml
Labels: feature

#175 Fix/170 jwt exction
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/exception/CustomAuthException.java
  backend/src/main/java/site/kkokkio/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
Labels: bug

#173 feat: add keyword mocking data at GoogleTrendsRssService
  backend/src/main/java/site/kkokkio/domain/keyword/repository/KeywordMetricHourlyRepository.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/GoogleTrendsRssService.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/global/init/BaseInitData.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mock/keywords.txt
  backend/src/test/java/site/kkokkio/domain/keyword/service/GoogleTrendsRssServiceTest.java
Labels: feature, refactor

#171 Bug/160 fix video top api
  backend/src/main/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/dto/KeywordMetricHourlyResponse.java
  backend/src/main/java/site/kkokkio/domain/keyword/dto/KeywordMetricHourlyDto.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyService.java
  backend/src/main/java/site/kkokkio/domain/source/controller/SourceControllerV1.java
  backend/src/main/java/site/kkokkio/domain/source/dto/TopSourceItemDto.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/main/java/site/kkokkio/global/config/WebClientConfig.java
  backend/src/test/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
Labels: bug, refactor

#177 Release(production): v1.0.3 MVP-1 release
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/dto/KeywordMetricHourlyResponse.java
  backend/src/main/java/site/kkokkio/domain/keyword/dto/KeywordMetricHourlyDto.java
  backend/src/main/java/site/kkokkio/domain/keyword/repository/KeywordMetricHourlyRepository.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/GoogleTrendsRssService.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyService.java
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/AuthService.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/domain/source/controller/SourceControllerV1.java
  backend/src/main/java/site/kkokkio/domain/source/dto/SourceDto.java
  backend/src/main/java/site/kkokkio/domain/source/dto/TopSourceItemDto.java
  backend/src/main/java/site/kkokkio/domain/source/repository/PostSourceRepository.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/config/WebClientConfig.java
  backend/src/main/java/site/kkokkio/global/dto/RsData.java
  backend/src/main/java/site/kkokkio/global/exception/CustomAuthException.java
  backend/src/main/java/site/kkokkio/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/main/java/site/kkokkio/global/init/BaseInitData.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/mock/keywords.txt
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/keyword/service/GoogleTrendsRssServiceTest.java
  backend/src/test/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyServiceTest.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
  package-lock.json
  package.json
Labels: release

#191 Bug/187 get post top revision
  backend/src/main/java/site/kkokkio/domain/admin/controller/BatchJobControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/repository/KeywordMetricHourlyRepository.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV1.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/global/init/BaseInitData.java
  backend/src/main/java/site/kkokkio/global/scheduler/HourScheduler.java
  backend/src/main/resources/application.yml
  backend/src/test/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyServiceTest.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: bug, chore

#194 Feat/183 setup auth preauthorize custom annotation
  backend/src/main/java/site/kkokkio/domain/admin/controller/BatchJobControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/keyword/controller/GoogleTrendsController.java
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/auth/AuthChecker.java
  backend/src/main/java/site/kkokkio/global/auth/CustomUserDetails.java
  backend/src/main/java/site/kkokkio/global/auth/CustomUserDetailsService.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsActiveMember.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsAdmin.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsCommentActiveOwner.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsCommentOwner.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsSelf.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/filter/JwtAuthenticationFilter.java
  backend/src/test/java/site/kkokkio/domain/admin/controller/BatchJobControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/keyword/controller/KeywordMetricHourlyControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/controller/AuthControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/source/controller/SourceControllerV1Test.java
Labels: feature

#197 Feat/179 add post report
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV2.java
  backend/src/main/java/site/kkokkio/domain/comment/entity/CommentReport.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentReportRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV2.java
  backend/src/main/java/site/kkokkio/domain/post/dto/PostReportRequestDto.java
  backend/src/main/java/site/kkokkio/domain/post/entity/Post.java
  backend/src/main/java/site/kkokkio/domain/post/entity/PostReport.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostReportRepository.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/domain/report/entity/CommentReport.java
  backend/src/main/java/site/kkokkio/global/enums/ReportReason.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/main/java/site/kkokkio/infra/batch/WIP_SearchVideosTasklet.java
  backend/src/main/resources/db/migration/V2__add_report_count_to_comment.sql
  backend/src/main/resources/db/migration/V2__add_report_tables.sql
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: feature

#196 feat : 회원정보 수정 및 비밀번호 검증 api 작성 + test 코드 작성
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/MemberUpdateRequest.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/PasswordVerificationRequest.java
  backend/src/main/java/site/kkokkio/domain/member/service/AuthService.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
Labels: feature, test

#198 Feat/184 add admin user
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV2.java
  backend/src/main/java/site/kkokkio/domain/comment/dto/CommentReportRequest.java
  backend/src/main/java/site/kkokkio/domain/comment/entity/CommentReport.java
  backend/src/main/java/site/kkokkio/domain/member/controller/AdminMemberControllerV2.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/AdminMemberListResponse.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/AdminMemberResponse.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/AdminMemberRoleUpdateRequest.java
  backend/src/main/java/site/kkokkio/domain/member/entity/Member.java
  backend/src/main/java/site/kkokkio/domain/member/repository/MemberRepository.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/site/kkokkio/domain/member/controller/AdminMemberControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV2Test.java
Labels: feature

#201 Feat/190 member delete
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV2.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/entity/Member.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsCommentActiveOwner.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
Labels: feature

#203 Feat/189 reset password
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/dto/PasswordResetRequest.java
  backend/src/main/java/site/kkokkio/domain/member/entity/Member.java
  backend/src/main/java/site/kkokkio/domain/member/service/MailService.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/test/java/site/kkokkio/domain/member/controller/AuthControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MailServiceTest.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
Labels: feature

#204 Feat/182 setup loki and promtail to grafana
  backend/.gitignore
  backend/docker-compose.yaml
  backend/loki-config.yaml
  backend/prometheus.yml
  backend/promtail-config.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: feature, test

#208 Refactor/202 auth refactor
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsActiveMember.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsAdmin.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsCommentActiveOwner.java
  backend/src/main/java/site/kkokkio/global/auth/annotations/IsCommentOwner.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/filter/JwtAuthenticationFilter.java
Labels: feature, refactor

#207 Feat/185 add admin comment
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV2.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/CommentReportRequest.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/ReportedCommentHideRequest.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/ReportedCommentListResponse.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/ReportedCommentResponse.java
  backend/src/main/java/site/kkokkio/domain/comment/dto/ReportedCommentSummary.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentReportRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
Labels: feature

#206 Feat/79 ai summary
  backend/src/main/java/site/kkokkio/KkokkioApplication.java
  backend/src/main/java/site/kkokkio/domain/post/port/out/AiSummaryPort.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/global/config/WebClientConfig.java
  backend/src/main/java/site/kkokkio/infra/ai/AiType.java
  backend/src/main/java/site/kkokkio/infra/ai/adapter/AiSummaryPortRouter.java
  backend/src/main/java/site/kkokkio/infra/ai/gemini/GeminiAiApiPort.java
  backend/src/main/java/site/kkokkio/infra/ai/gemini/GeminiApiProperties.java
  backend/src/main/java/site/kkokkio/infra/ai/gemini/dto/GeminiError.java
  backend/src/main/java/site/kkokkio/infra/ai/gemini/dto/GeminiErrorDetail.java
  backend/src/main/java/site/kkokkio/infra/ai/gemini/dto/GeminiErrorResponse.java
  backend/src/main/java/site/kkokkio/infra/ai/gemini/dto/GeminiResponse.java
  backend/src/main/java/site/kkokkio/infra/ai/prompt/AiSystemPromptResolver.java
  backend/src/main/java/site/kkokkio/infra/ai/prompt/DefaultAiSystemPromptResolver.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/mock/gemini-summary.json
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
  backend/src/test/java/site/kkokkio/infra/ai/gemini/GeminiAiAdapterMockTest.java
  backend/src/test/java/site/kkokkio/infra/ai/gemini/GeminiAiAdapterTest.java
Labels: feature

#216 refactor: GoogleTrendsRssService.java port/adapter 형식으로 변경
  backend/src/main/java/site/kkokkio/domain/keyword/controller/GoogleTrendsController.java
  backend/src/main/java/site/kkokkio/domain/keyword/port/out/TrendsPort.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/TrendsService.java
  backend/src/main/java/site/kkokkio/global/config/BatchConfig.java
  backend/src/main/java/site/kkokkio/infra/google/trends/GoogleTrendsAdapter.java
  backend/src/main/java/site/kkokkio/infra/google/trends/dto/KeywordInfo.java
  backend/src/main/resources/application.yml
  backend/src/test/java/site/kkokkio/domain/keyword/service/TrendsServiceTest.java
Labels: refactor

#215 Fix/210 authentication optimization
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV2.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/MemberService.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV2.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/global/auth/AuthChecker.java
  backend/src/main/java/site/kkokkio/global/auth/CustomUserDetails.java
  backend/src/main/java/site/kkokkio/global/auth/CustomUserDetailsService.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/main/java/site/kkokkio/global/filter/JwtAuthenticationFilter.java
  backend/src/test/java/site/kkokkio/domain/admin/controller/BatchJobControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MemberServiceV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: feature

#219 fix: remove logback console and fix application warning
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
Labels: bug

#220 Feat/186 add admin post
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV1.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV2.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/PostListResponse.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/PostReportRequest.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/ReportedPostHideRequest.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/ReportedPostListResponse.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/ReportedPostResponse.java
  backend/src/main/java/site/kkokkio/domain/post/dto/ReportedPostSummary.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostReportRepository.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/global/exception/doc/ErrorCode.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: feature

#221 Feat/57 update spring batch from fetchTrendingKeywords to searchSources
  backend/prometheus.yml
  backend/src/main/java/site/kkokkio/domain/batch/TrendToPostJobConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/context/BatchConstants.java
  backend/src/main/java/site/kkokkio/domain/batch/context/ExecutionContextKeys.java
  backend/src/main/java/site/kkokkio/domain/batch/context/JobParameterKeys.java
  backend/src/main/java/site/kkokkio/domain/batch/decider/NoveltyDeciderConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/flow/SearchSourcesFlowConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/listener/BatchMetricsListener.java
  backend/src/main/java/site/kkokkio/domain/batch/listener/LogStepListener.java
  backend/src/main/java/site/kkokkio/domain/batch/step/CachePostStepConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/step/EvaluateNoveltyStepConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/step/FetchTrendingKeywordsStepConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/step/GeneratePostStepConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/step/SearchNewsStepConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/step/SearchVideosStepConfig.java
  backend/src/main/java/site/kkokkio/domain/keyword/dto/NoveltyStatsDto.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyService.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostKeywordRepository.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/domain/source/dto/SearchStatsDto.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/main/java/site/kkokkio/global/config/BatchConfig.java
  backend/src/main/java/site/kkokkio/global/exception/ExternalApiException.java
  backend/src/main/java/site/kkokkio/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/site/kkokkio/infra/google/trends/GoogleTrendsAdapter.java
  backend/src/main/resources/application.yml
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: feature, refactor

#224 Update V2__add_report_tables.sql
  backend/src/main/resources/db/migration/V2__add_report_tables.sql
Labels: bug

#226 refactor: 모든 서버 및 컨테이너 타임존 변경
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prd.yml
  infra/dev/main.tf
  infra/prd/main.tf
Labels: chore

#238 Feat/234 resolve comment
  backend/src/main/java/site/kkokkio/domain/comment/dto/CommentDto.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
Labels: feature

#241 Bug/232 none cookie
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/controller/MemberControllerV1.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
  backend/src/test/java/site/kkokkio/domain/member/controller/MemberControllerV1Test.java
Labels: bug

#243 Feat/240 add etc
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV2.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/CommentReportRequest.java
  backend/src/main/java/site/kkokkio/domain/comment/entity/CommentReport.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV2.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/PostReportRequest.java
  backend/src/main/java/site/kkokkio/domain/post/entity/PostReport.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/resources/db/migration/V3__add_etc_reason_to_reports.sql
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
  backend/src/test/java/site/kkokkio/infra/batch/TrendingKeywordsJobTests.java
Labels: feature

#245 Fix/244 modify thumnail url
  backend/src/main/java/site/kkokkio/domain/source/controller/dto/SourceListResponse.java
Labels: bug

#248 Feat/229 spring batch test
  backend/build.gradle
  backend/src/main/java/site/kkokkio/domain/batch/context/ExecutionContextKeys.java
  backend/src/main/java/site/kkokkio/domain/batch/context/MetricsKeys.java
  backend/src/main/java/site/kkokkio/domain/batch/decider/NoveltyDeciderConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/listener/BatchMetricsListener.java
  backend/src/main/java/site/kkokkio/domain/batch/step/CachePostStepConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/step/EvaluateNoveltyStepConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/step/FetchTrendingKeywordsStepConfig.java
  backend/src/main/java/site/kkokkio/domain/batch/step/GeneratePostStepConfig.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/TrendsService.java
  backend/src/main/java/site/kkokkio/domain/source/service/SourceService.java
  backend/src/main/java/site/kkokkio/infra/google/trends/GoogleTrendsAdapter.java
  backend/src/test/java/site/kkokkio/KkokkioApplicationTests.java
  backend/src/test/java/site/kkokkio/domain/batch/TrendToPostJobConfigTest.java
  backend/src/test/java/site/kkokkio/domain/batch/decider/NoveltyDeciderConfigTest.java
  backend/src/test/java/site/kkokkio/domain/batch/flow/SearchSourcesFlowConfigTest.java
  backend/src/test/java/site/kkokkio/domain/batch/listener/BatchMetricsListenerTest.java
  backend/src/test/java/site/kkokkio/domain/batch/step/CachePostStepConfigTest.java
  backend/src/test/java/site/kkokkio/domain/batch/step/EvaluateNoveltyStepConfigTest.java
  backend/src/test/java/site/kkokkio/domain/batch/step/FetchTrendingKeywordsStepConfigTest.java
  backend/src/test/java/site/kkokkio/domain/batch/step/GeneratePostStepConfigTest.java
  backend/src/test/java/site/kkokkio/domain/batch/step/SearchNewsStepConfigTest.java
  backend/src/test/java/site/kkokkio/domain/batch/step/SearchVideosStepConfigTest.java
  infra/grafana/dashboard/batch.json
Labels: refactor, test

#250 fix: update grafana batch dashboard
  backend/src/main/java/site/kkokkio/domain/batch/context/MetricsKeys.java
  backend/src/main/java/site/kkokkio/domain/batch/listener/BatchMetricsListener.java
  backend/src/main/resources/application.yml
  backend/src/test/java/site/kkokkio/domain/batch/listener/BatchMetricsListenerTest.java
  infra/grafana/dashboard/batch.json
Labels: chore

#251 Feat/180 update readme & conventions
  README.md
  docs/CODE_CONVENTION.md
  docs/CONTRIBUTING.md
Labels: docs

#256 Bug/253 flyway migrate fix
  .github/workflows/deploy-common.yml
Labels: build

#261 Fix/260 admin comment, post list fix
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV2.java
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/ReportedCommentResponse.java
  backend/src/main/java/site/kkokkio/domain/comment/dto/ReportedCommentSummary.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentReportRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV2.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/ReportedPostResponse.java
  backend/src/main/java/site/kkokkio/domain/post/dto/ReportedPostSummary.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostReportRepository.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
  backend/src/test/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyServiceTest.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV2Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
Labels: bug

#263 feat: 150 character limit
  backend/src/main/java/site/kkokkio/domain/comment/controller/dto/CommentCreateRequest.java
Labels: feature

#265 refactor: 점수 음수 오류로 인한 필드 기본값 변경, 포스트가 생성되지 않는 실시간 키워드의 postid 추가
  backend/src/main/java/site/kkokkio/domain/keyword/entity/KeywordMetricHourly.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyService.java
  backend/src/test/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyServiceTest.java
Labels: bug, refactor

#268 Bug/266 fix promtail config with mutiline
  backend/promtail-config.yml
  backend/src/main/resources/logback-spring.xml
Labels: bug

#270 fix: modified to always return success when logout
  backend/src/main/java/site/kkokkio/domain/member/service/AuthService.java
  backend/src/main/java/site/kkokkio/global/filter/JwtAuthenticationFilter.java
Labels: bug

#272 refactor: 스코어 버그 가능성 해결, 스코어 단위 조정
  backend/src/main/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyService.java
  backend/src/main/java/site/kkokkio/domain/keyword/service/TrendsService.java
  backend/src/test/java/site/kkokkio/domain/keyword/service/KeywordMetricHourlyServiceTest.java
Labels: bug, refactor

#276 fix: 볼륨 설정
  .github/workflows/deploy-common.yml
Labels: bug

#280 Test/278 dev server mocking data
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
  backend/src/main/resources/application-dev.yml
Labels: test

#283 bug: 비밀번호 인증이 안되는 버그 해결
  backend/src/main/java/site/kkokkio/domain/member/service/AuthService.java
Labels: bug

#286 Refactor/285 login message change
  backend/src/main/java/site/kkokkio/domain/member/controller/AdminMemberControllerV2.java
  backend/src/main/java/site/kkokkio/global/config/SecurityConfig.java
Labels: style

#289 Bug/288 comment fix
  backend/src/main/java/site/kkokkio/domain/comment/controller/CommentControllerV1.java
  backend/src/main/java/site/kkokkio/domain/comment/dto/CommentDto.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentLikeRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/global/auth/AuthChecker.java
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/comment/service/CommentServiceTest.java
Labels: bug

#300 Bug/299 report flag
  backend/src/main/java/site/kkokkio/domain/comment/dto/CommentDto.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV1.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV2.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/PostDetailResponse.java
  backend/src/main/java/site/kkokkio/domain/post/dto/PostDto.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
Labels: bug

#304 Release(production): v2.0.5 MVP-2 release
  backend/src/main/java/site/kkokkio/domain/comment/dto/CommentDto.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/member/controller/AuthControllerV1.java
  backend/src/main/java/site/kkokkio/domain/member/service/MailService.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV1.java
  backend/src/main/java/site/kkokkio/domain/post/controller/PostControllerV2.java
  backend/src/main/java/site/kkokkio/domain/post/controller/dto/PostDetailResponse.java
  backend/src/main/java/site/kkokkio/domain/post/dto/PostDto.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/global/filter/JwtAuthenticationFilter.java
  backend/src/main/java/site/kkokkio/global/util/JwtUtils.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/site/kkokkio/domain/comment/controller/CommentControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/controller/AuthControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/member/service/MailServiceTest.java
  backend/src/test/java/site/kkokkio/domain/post/controller/PostControllerV1Test.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
  backend/src/test/java/site/kkokkio/domain/source/service/SourceServiceTest.java
Labels: release

#310 테라폼 환경 생성 시 user_data의 docker-compose에서 네트워크 이름을 common으로 고정
  infra/dev/main.tf
  infra/prd/main.tf
Labels: feature

#311 Release(production): v2.0.6 MVP-2 release
  backend/src/main/java/site/kkokkio/domain/comment/repository/CommentReportRepository.java
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostReportRepository.java
  backend/src/main/java/site/kkokkio/domain/post/repository/PostRepository.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/test/java/site/kkokkio/domain/post/service/PostServiceTest.java
  infra/dev/main.tf
  infra/prd/main.tf
Labels: release

#313 Fix/312 fix youtube url
  backend/src/main/java/site/kkokkio/domain/source/dto/VideoDto.java
Labels: bug

#317 Fix/316 korean search
  backend/src/main/java/site/kkokkio/domain/comment/service/CommentService.java
  backend/src/main/java/site/kkokkio/domain/post/service/PostService.java
  backend/src/main/java/site/kkokkio/global/enums/ReportReason.java
Labels: bug
